/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

import org.example.uiController.UIController;

public class CSUBatchApplication {
    public String getGreeting() {
        return "System Loading...";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(new CSUBatchApplication().getGreeting());
         UIController UI = new UIController(new Scanner(System.in));
         UI.generateUI();
         UI.userInteraction();
    }
}
