/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Unit tests for the CSUBatchApplication class.
 */
class CSUBatchApplicationTest {
    @Test
    @DisplayName("Should successfully display a greeting when the application is started.")
    public void testCSUBatchApplicationHasAGreeting() {
        // Arrange
        CSUBatchApplication classUnderTest = new CSUBatchApplication();

        // Act
        String greeting = classUnderTest.getGreeting();

        // Assert
        assertNotNull(greeting, "app should have a greeting");
    }
}
