/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CSUBatchApplicationTest {
    @Test void appHasAGreeting() {
        CSUBatchApplication classUnderTest = new CSUBatchApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
